# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               App Developer
tagline:             'Learning Materials'
description:         'Learning materials for the RED Academy App Developer Professional Program.'
url:                 https://red-adp.herokuapp.com
baseurl:             ''
paginate:            10
paginate_path:       '/news/page:num/'

# About/contact
author:
  name:              Mandi Wise (forked from Mark Otto)
  url:               https://twitter.com/mandiwise
  email:             mandi@redacademy.com

# Custom vars
version:             1.2.2
github:
  repo:              https://github.com/redacademy/adp-vancouver

# Collections
collections:
   lessons:
      output: true
      permalink: /lesson/:title/
   slides:
      output: true
      permalink: /slides/:title/
   projects:
      output: true
      permalink: /project/:title/

jekyll_auth:
  ssl: true

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to un-minify using :expanded

# Markdown Processors
markdown: RedcarpetExt
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions: ['smart', 'tables', 'autolink', 'fenced_code_blocks']

# Plugins
gems: ['jekyll-paginate', 'redcarpet']

# Exclusions
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'README.md', 'LICENSE.md', 'CONTRIBUTING.md', 'installation.md']
