# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Web Developer Essentials Learning Materials
tagline:             'by RED Academy'
description:         'Learning materials for the RED Academy Web Developer Essentials course.'
url:                 http://redacademy.com
baseurl:             ''
paginate:            10
paginate_path:       '/news/page:num/'

# About/contact
author:
  name:              Mandi Wise (forked from Mark Otto)
  url:               https://twitter.com/mandiwise
  email:             mandi@redacademy.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/redacademy/web-dev-essentials

# Collections
collections:
   lessons:
      output: true
   slides:
      output: true

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to un-minify using :expanded

# Exclusions
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'README.md', 'LICENSE.md', 'CONTRIBUTING.md', 'installation.md']
