# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               App Developer
tagline:             'Learning Materials'
description:         'Learning materials for the RED Academy App Developer Professional Program.'
url:                 http://red-van-adp.herokuapp.com
baseurl:             ''
paginate:            10
paginate_path:       '/news/page:num/'

# About/contact
author:
  name:              Mandi Wise (forked from Mark Otto)
  url:               https://twitter.com/mandiwise
  email:             mandi@redacademy.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/redacademy/adp-vancouver

# Collections
collections:
   lessons:
      output: true
      permalink: /lesson/:title/
   slides:
      output: true
      permalink: /slides/:title/
   projects:
      output: true
      permalink: /project/:title/

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to un-minify using :expanded

# Markdown Processors
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions: ['smart', 'tables', 'autolink']

# Plugins
gems: ['jekyll-paginate', 'redcarpet']

# Exclusions
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'README.md', 'LICENSE.md', 'CONTRIBUTING.md', 'installation.md']

current: "2016-fall"
courses:
  2016-fall:
    Intro to Web Applications: '2016-09-26'
    React Components, State & Events: '2016-09-27'
    React Props: '2016-09-28'
    React Lifecycle Methods: '2016-09-29'
    React Inline Styles: '2016-09-29'
    Redux: '2016-10-03'
    Functional Programming: '2016-10-04'
    Redux Middleware: '2016-10-05'
    React and Redux: '2016-10-06'
    Web Server: '2016-10-11'
    Connecting Client & Server: '2016-10-11'
    Async Javascript: '2016-10-12'
    Intro to Databases with SQL: '2016-10-17'
    Validating Data with Schema: '2016-10-18'
    Forms: '2016-10-19'
    Validating & Sanitizing Data: '2016-10-20'
    User Sessions & Accounts: '2016-10-21'
